# Generated by Django 3.0.2 on 2020-05-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno1', models.CharField(max_length=30)),
                ('eno2', models.CharField(max_length=30)),
                ('eno3', models.CharField(max_length=30)),
                ('eno4', models.CharField(max_length=30)),
                ('eno5', models.CharField(max_length=30)),
                ('eno6', models.CharField(max_length=30)),
                ('eno7', models.CharField(max_length=30)),
                ('eno8', models.CharField(max_length=30)),
                ('eno9', models.CharField(max_length=30)),
            ],
        ),
    ]
