# Generated by Django 3.0.3 on 2020-05-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odessy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en', models.CharField(max_length=30)),
            ],
        ),
    ]
