# Generated by Django 3.0.3 on 2020-05-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odessy', '0002_hell'),
    ]

    operations = [
        migrations.CreateModel(
            name='od',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en1', models.CharField(max_length=30)),
                ('en2', models.CharField(max_length=30)),
                ('en3', models.CharField(max_length=30)),
                ('en4', models.CharField(max_length=30)),
                ('en5', models.CharField(max_length=30)),
                ('en6', models.CharField(max_length=30)),
                ('en7', models.CharField(max_length=30)),
                ('en8', models.CharField(max_length=30)),
                ('en9', models.CharField(max_length=30)),
                ('en10', models.CharField(max_length=30)),
            ],
        ),
    ]
